[package]
name = "RllamaR"
version = "0.1.0"
edition = "2021"

[dependencies]
clap = { version = "4.5.21", features = ["derive"] }
actix-web = "4"
actix-http = "3"
actix = "0.13"
log="0.4"
hf-hub = { git = "https://github.com/oovm/hf-hub" }
anyhow = "1"
tokenizers = { version = "0.19.1", features = ["onig"] }
candle-core = "0.8.0"
candle-nn = "0.8.0"
candle-transformers = "0.8.0"
serde = {version = "1", features = ["derive","rc"]}
serde_json = "1"
serde_urlencoded = "0.6"
